
[{"cedula":"1082963607","nombres":"Genesis ","apellidos":"Guerreo Martinez","tipoEmpleado":"Supervisor"},{"cedula":"1082765394","nombres":"Jose Luis","apellidos":"Echavez Morales","tipoEmpleado":"Aseador"},{"cedula":"1082666","nombres":"Andres","apellidos":"Vasquez Zu\u00f1iga","tipoEmpleado":"Cigarron"},{"cedula":"1082777","nombres":"Francisco Rucutundo","apellidos":"Velasquez","tipoEmpleado":"Empacador"}]